Environment:
  StackName: sam-stream-consumer-test
  Region: us-west-2
  Profile: default
  DeploymentBucket: deployment.us-west-2
  DeploymentPrefix: sam-stream-consumer/test
CloudFormation:
  EnvironmentName: test
  ExampleTableStreamArn: arn:aws:dynamodb:us-west-2:account-id:table/ExampleTableWithStream/stream/2015-06-27T00:48:05.899
  StreamConsumerMemorySizeInMb: 128
  StreamConsumerTimeoutInSeconds: 10
  StreamConsumerLogRetentionInDays: 7
Tags:
  Application: sam-stream-consumer
  Environment: test
  Email: jim.gisler@gmail.com
